### ISSUE TITLE
探讨Dubbo与Swagger的集成

### ISSUE THREAD

**Issue by Sayi** [Sayi/sayi.github.com#15]

**Comment by sakunon** [comment]
正好需要，非常感谢作者开源

**Comment by Sayi** [comment]
@sakunon 目前还是alpha版本，欢迎共同来完善。-:)

**Comment by ZoonChen** [comment]
HttpMatch 中的 findRefMethods(Method[] interfaceMethods, String operationId,String requestMethod) 方法 Collections.sort(ret, new Comparator<Method>() {
			@Override
			public int compare(Method o1, Method o2) {
				return o2.getParameterCount() - o1.getParameterCount();
			}
		}); 
getParameterCount（）方法 没有定义

**Comment by hfq-yangyang-yangyang** [comment]
能否支持springfox

**Comment by hfq-yangyang-yangyang** [comment]
用的 docker swaggerapi/swagger-ui
输入input框 http://10.10.11.180:12102/swagger-dubbo/swagger.json 点击 explore按钮。
发现一个不能跨域的问题，
加了 @CrossOrigin(origins = "*")

@Controller
@CrossOrigin(origins = "*")
@RequestMapping("${swagger.dubbo.doc:swagger-dubbo}")
@Api(hidden = true)
public class SwaggerDubboController {

**Comment by hfq-yangyang-yangyang** [comment]
跨域解决后就是

https://github.com/Sayi/swagger-dubbo/issues/13

**Comment by lennon1994** [comment]
我这里启动报错，无奈

**Comment by Sayi** [comment]
swagger-dubbo V2.0.1 更新日志：
* 支持最新的dubbo注解方式(@dubbocomponentscan)的服务发现
* 修复某些情况下Swagger数据以JSON格式暴露，而不是String
* Spring boot 示例
* 跨域支持的一种解决方案
* 修复若干BUG

**Comment by Redick01** [comment]
你好，支持dubbo2.8.4吗？我这边启动报错～

**Comment by Redick01** [comment]
您好，说下我这变报错的具体信息吧，是创建DubboPropertyConfig这个bean的时候报错，大概是DubboPropertyConfig注入ServletContext的时候找不到要注入的Class，我这边是使用的dubbo2.8.4，并且使用的是tomcat插件通过dubbo发布http服务。

**Comment by Sayi** [comment]
@Redick01  目前官方dubbo最新版本是2.6.2。你的项目应该缺少这个pom：
```xml
<dependency>
    <groupId>javax.servlet</groupId>
    <artifactId>javax.servlet-api</artifactId>
    <version>3.0.1</version>
</dependency>
```

**Comment by Redick01** [comment]
很高兴您能回复我，我在这个之前也试过添加这个依赖包，依然报错。以下是我报错的具体信息，麻烦您抽空看下～
Exception in thread "main" org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'dubboPropertyConfig': Injection of autowired dependencies failed; nested exception is org.springframework.beans.factory.BeanCreationException: Could not autowire field: private javax.servlet.ServletContext com.deepoove.swagger.dubbo.config.DubboPropertyConfig.servletContext; nested exception is org.springframework.beans.factory.NoSuchBeanDefinitionException: No qualifying bean of type [javax.servlet.ServletContext] found for dependency: expected at least 1 bean which qualifies as autowire candidate for this dependency. Dependency annotations: {@org.springframework.beans.factory.annotation.Autowired(required=true)}
	at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor.postProcessPropertyValues(AutowiredAnnotationBeanPostProcessor.java:334)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.populateBean(AbstractAutowireCapableBeanFactory.java:1210)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:537)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:476)
	at org.springframework.beans.factory.support.AbstractBeanFactory$1.getObject(AbstractBeanFactory.java:303)
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:230)
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:299)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:194)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:755)
	at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:757)
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:480)
	at org.springframework.context.support.ClassPathXmlApplicationContext.<init>(ClassPathXmlApplicationContext.java:139)
	at org.springframework.context.support.ClassPathXmlApplicationContext.<init>(ClassPathXmlApplicationContext.java:93)
	at com.ruubypay.MainClass.main(MainClass.java:27)
Caused by: org.springframework.beans.factory.BeanCreationException: Could not autowire field: private javax.servlet.ServletContext com.deepoove.swagger.dubbo.config.DubboPropertyConfig.servletContext; nested exception is org.springframework.beans.factory.NoSuchBeanDefinitionException: No qualifying bean of type [javax.servlet.ServletContext] found for dependency: expected at least 1 bean which qualifies as autowire candidate for this dependency. Dependency annotations: {@org.springframework.beans.factory.annotation.Autowired(required=true)}
	at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor$AutowiredFieldElement.inject(AutowiredAnnotationBeanPostProcessor.java:561)
	at org.springframework.beans.factory.annotation.InjectionMetadata.inject(InjectionMetadata.java:88)
	at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor.postProcessPropertyValues(AutowiredAnnotationBeanPostProcessor.java:331)
	... 13 more
Caused by: org.springframework.beans.factory.NoSuchBeanDefinitionException: No qualifying bean of type [javax.servlet.ServletContext] found for dependency: expected at least 1 bean which qualifies as autowire candidate for this dependency. Dependency annotations: {@org.springframework.beans.factory.annotation.Autowired(required=true)}
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.raiseNoSuchBeanDefinitionException(DefaultListableBeanFactory.java:1301)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.doResolveDependency(DefaultListableBeanFactory.java:1047)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.resolveDependency(DefaultListableBeanFactory.java:942)
	at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor$AutowiredFieldElement.inject(AutowiredAnnotationBeanPostProcessor.java:533)
	... 15 more

**Comment by Sayi** [comment]
@Redick01 你是用Main方法启动的，缺少web容器。

HTTP模拟请求需要Web容器。

**Comment by hfq-yangyang-yangyang** [comment]
问题解决，你们说的都不对

**Comment by xujunhua555** [comment]
我有个疑问，我目前很多项目上都有dubbo服务，那么我现在想把这些dubbo服务都统一放到swagger-dubbo这个webapp中进行统一展现，这该如何优雅的实现

**Comment by Sayi** [comment]
@xujunhua555 我的想法是通过Zookeeper去发现这些服务，然后通过swagger-dubbo暴露API文档。

**Comment by xujunhua555** [comment]
您好！
是的，这是个办法，但是目前你github上的代码还没实现这样的需求吧？能否加个qq探讨下呢？我qq1139273516 我也是杭州上班的


原始邮件
发件人:卅一notifications@github.com
收件人:Sayi/sayi.github.comsayi.github.com@noreply.github.com
抄送:xujunhua555xujunhua555@163.com; Mentionmention@noreply.github.com
发送时间:2018年7月11日(周三) 09:42
主题:Re: [Sayi/sayi.github.com] 探讨Dubbo与Swagger的集成 (#15)


@xujunhua555 我的想法是通过Zookeeper去发现这些服务，然后通过swagger-dubbo暴露API文档。

**Comment by lizwmaster** [comment]
在使用dubbo2.5.3(公司硬性要求)和Spring boot整合时，发现ReferenceManager中从ServiceBean时，取不到，有遇到这种情况吗

**Comment by finduuu** [comment]
为什么http://localhost:8080/yyzt-web-pack-2.0/swagger-dubbo/swagger.json 这个接口返回的是404
这个是swagger-dubbo.properties的配置
swagger.dubbo.doc=swagger-dubbo
swagger.dubbo.http=h

swagger.dubbo.application.version = 2.0
swagger.dubbo.application.groupId = com.myhexin.yyzt
swagger.dubbo.application.artifactId = yyzt-cbas-api

#rpc or local
swagger.dubbo.cluster = rpc

swagger.dubbo.enable = true

@Sayi

**Comment by finduuu** [comment]
为什么http://localhost:8080/项目名称/swagger-dubbo/swagger.json 这个接口返回的是404，地址错了吗
这个是swagger-dubbo.properties的配置
swagger.dubbo.doc=swagger-dubbo
swagger.dubbo.http=h

swagger.dubbo.application.version = 2.0
swagger.dubbo.application.groupId = com.myhexin.yyzt
swagger.dubbo.application.artifactId = yyzt-cbas-api

#rpc or local
swagger.dubbo.cluster = rpc

swagger.dubbo.enable = true

@Sayi

**Comment by TheNorthMemory** [comment]
[Java零注入 DUBBO+SWAGGER纯前端集成方案](https://github.com/TheNorthMemory/dubbo-swagger)，只要会写OAS2，就能消费服务
